export interface GameAssetInterface {
  images: string[];
}

export const images = [
  "illustrate",
  "leg",
  "pie",
  "random",
  "talk",
  "organix",
  "spoon",
  "regular",
  "phone",
  "cord",
  "chopsticks",
  "whine",
  "wine",
  "millie",
  "database",
  "failure",
  "puzzle",
  "sreenshot",
  "game",
  "sick",
  "literal",
  "async",
  "identifier",
  "process",
  "input",
  "file",
  "time",
  "verify",
  "baby",
  "lounge",
  "heaven",
  "clouds",
  "resilience",
  "folder",
  "android",
  "apple",
  "class",
  "outer",
  "space",
  "improved",
  "screen",
  "saver",
  "black",
  "socket",
  "meeting",
  "remote",
  "battery",
  "television",
  "candle",
  "kite",
  "johnny",
  "music",
  "sponge",
  "zebra",
  "lines",
  "crossing",
  "steady",
  "dance",
  "archive",
  "documentspdf",
  "trees",
  "oxygen",
  "spider",
  "encrypted",
  "Kaleigh",
  "Jamar",
  "Lucie",
  "Nyah",
  "Shirley",
  "Tre",
  "Violet",
  "Collin",
  "Josie",
  "Buford",
  "Talia",
  "Dena",
  "Brice",
  "Barry",
  "Columbus",
  "Marielle",
  "Hillary",
  "Ruben",
  "Florine",
  "Sheridan",
  "Kristy",
  "Marcel",
  "Khalil",
  "Guiseppe",
  "Jake",
  "Clint",
  "Mia",
  "Blake",
  "Bryana",
  "Demario",
  "Kathryne",
  "Ramona",
  "Devin",
  "Sigurd",
  "Monica",
  "Adah",
  "Margret",
  "Khalid",
  "Hermina",
  "Whitney",
  "Ruthie",
  "Lacey",
  "Kira",
  "Elsa",
  "Jennyfer",
  "Michael",
  "Jaydon",
  "Linda",
  "Alfreda",
  "Alexie",
  "Katarina",
  "Cale",
  "Stefan",
  "Chad",
  "Shawn",
  "Gilbert",
  "Rhianna",
  "Marietta",
  "Jarret",
  "Agustin",
  "Alan",
  "Herminia",
  "Andre",
  "Reta",
  "Etha",
  "Isabel",
  "Stan",
  "Kayden",
  "Deven",
  "Nick",
  "Yadira",
  "Marilou",
  "Gia",
  "Karen",
  "Macie",
  "Fern",
  "Alexys",
  "Theresa",
  "Cheyanne",
  "Eugenia",
  "Godfrey",
  "Christina",
  "Abbey",
  "Cristina",
  "Chanel",
  "Reynold",
  "Naomie",
  "Olga",
  "Rigoberto",
  "Estel",
  "Ismael",
  "Fidel",
  "Tia",
  "Jett",
  "Dannie",
  "Jaron",
  "Queenie",
  "Theron",
  "Abby",
  "Skyla",
  "Horace",
  "Kadin",
  "Juanita",
  "Mandy",
  "Elliot",
  "Karley",
  "Vita",
  "Oren",
  "Jayson",
  "Alexa",
  "Bertha",
  "Lenore",
  "Demetrius",
  "Anika",
  "Vern",
  "Kennith",
  "Romaine",
  "Murl",
  "Fannie",
  "Rex",
  "Kaela",
  "Lafayette",
  "Hope",
  "Ludwig",
  "Alvah",
  "Florence",
  "Josiane",
  "Emmalee",
  "Victor",
  "Junius",
  "Ambrose",
  "Alysha",
  "Alivia",
  "Mortimer",
  "Austin",
  "Novella",
  "Rosalee",
  "Andreanne",
  "Ava",
  "Rasheed",
  "Gina",
  "Evan",
  "Delta",
  "Rashawn",
  "Stuart",
  "Ryan",
  "Ayana",
  "Alvis",
  "Lou",
  "Raymond",
  "Lily",
  "Justen",
  "Royal",
  "Abdul",
  "Lessie",
  "Joshua",
  "Tod",
  "Mozell",
  "Jaylin",
  "Emilio",
  "Brandyn",
  "Asa",
  "Zoey",
  "Alena",
  "Maybelle",
  "Mikel",
  "Molly",
  "Eliane",
  "Dixie",
  "Ward",
  "Emmanuel",
  "Kaylin",
  "Joe",
  "Kameron",
  "Karianne",
  "Ahmad",
  "Oliver",
  "Charlie",
  "Tobin",
  "Amya",
  "Geovanny",
  "Edward",
  "Dessie",
  "Penelope",
  "Louisa",
  "Bella",
  "Marquise",
  "Kenna",
  "Kamren",
  "Rogers",
  "Kelly",
  "Tito",
  "Hassan",
  "Reginald",
  "Gaston",
  "Jaylan",
  "Milford",
  "Aletha",
  "Melyna",
  "Lazaro",
  "Beau",
  "Kendall",
  "Jerel",
  "Jerrold",
  "Luther",
  "Dwight",
  "Madisen",
  "Noemie",
  "Dax",
  "Travon",
  "Jaylon",
  "Lourdes",
  "Julia",
  "Stephany",
  "Lorenzo",
  "Marcia",
  "Leila",
  "Ned",
  "Faustino",
  "Yvette",
  "Jammie",
  "Jayme",
  "Camden",
  "Sharon",
  "Dayana",
  "Corene",
  "Omer",
  "Daron",
  "Audie",
  "Mathilde",
  "Jermain",
  "Kirk",
  "Devyn",
  "Virgil",
  "Clemens",
  "Delia",
  "Lia",
  "Gail",
  "Jamir",
  "Aron",
  "Rebekah",
  "Wilford",
  "Mason",
  "Serena",
  "Judy",
  "Joan",
  "Chris",
  "Syble",
  "Bethany",
  "Mittie",
  "Soledad",
  "Willow",
  "Gennaro",
  "Carol",
  "Rolando",
  "Quinten",
  "Doug",
  "Freeman",
  "Laisha",
  "Eliezer",
  "Shanna",
  "Jedediah",
  "Colten",
  "Nicolette",
  "Bessie",
  "Emelia",
  "Dino",
  "Emerson",
  "Jean",
  "Arvid",
  "Cody",
  "Laury",
  "Ceasar",
  "Simeon",
  "Savion",
  "Elisabeth",
  "Jaime",
  "Loraine",
  "Norberto",
  "Jacklyn",
  "Beulah",
  "Janis",
  "Jovan",
  "Daija",
  "Gus",
];

const gameAsset = [
  {
    type: {
      row: 1,
      col: 3,
    },
    result: {
      inheadenHomePage: {
        images: images
          .slice(0, 3)
          .map((i) => `/assets/game/col3row1/inheadenhomepage/${i}.png`),
        default: "/assets/game/col3row1/inheadenhomepage/default.png",
      },
      denisInTechSpace: {
        images: [
          "/assets/game/col3row1/denisInTechSpace/suit.png",
          "/assets/game/col3row1/denisInTechSpace/killer.png",
          "/assets/game/col3row1/denisInTechSpace/integration.png",
        ],
        default: "/assets/game/col3row1/denisInTechSpace/default.png",
      },
      footer: {
        images: [
          "/assets/game/col3row1/footer/reliable.png",
          "/assets/game/col3row1/footer/breakdown.png",
          "/assets/game/col3row1/footer/punch.png",
        ],
        default: "/assets/game/col3row1/footer/default.png",
      },
    },
  },
  {
    type: {
      row: 2,
      col: 3,
    },
    result: {
      inheadenHomePage: {
        images: [
          "/assets/game/col3row2/inheadenhomepage/theorist.png",
          "/assets/game/col3row2/inheadenhomepage/hell.png",
          "/assets/game/col3row2/inheadenhomepage/morsel.png",
          "/assets/game/col3row2/inheadenhomepage/resignation.png",
          "/assets/game/col3row2/inheadenhomepage/negative.png",
          "/assets/game/col3row2/inheadenhomepage/wonder.png",
        ],
        default: "/assets/game/col3row1/inheadenhomepage/default.png",
      },
      denisInTechSpace: {
        images: [
          "/assets/game/col3row2/denisInTechSpace/integration.png",
          "/assets/game/col3row2/denisInTechSpace/killer.png",
          "/assets/game/col3row2/denisInTechSpace/suit.png",
          "/assets/game/col3row2/denisInTechSpace/strategic.png",
          "/assets/game/col3row2/denisInTechSpace/moon.png",
          "/assets/game/col3row2/denisInTechSpace/marble.png",
        ],
        default: "/assets/game/col3row2/denisInTechSpace/default.png",
      },
      footer: {
        images: [
          "/assets/game/col3row2/footer/at.png",
          "/assets/game/col3row2/footer/flatware.png",
          "/assets/game/col3row2/footer/exclusive.png",
          "/assets/game/col3row2/footer/elbow.png",
          "/assets/game/col3row2/footer/exploit.png",
          "/assets/game/col3row2/footer/tool.png",
        ],
        default: "/assets/game/col3row1/footer/default.png",
      },
    },
  },
  {
    type: {
      row: 3,
      col: 3,
    },
    result: {
      inheadenHomePage: {
        images: [
          "/assets/game/col3row3/inheadenhomepage/theorist.png",
          "/assets/game/col3row3/inheadenhomepage/hell.png",
          "/assets/game/col3row3/inheadenhomepage/morsel.png",
          "/assets/game/col3row3/inheadenhomepage/resignation.png",
          "/assets/game/col3row3/inheadenhomepage/negative.png",
          "/assets/game/col3row3/inheadenhomepage/wonder.png",
          "/assets/game/col3row3/inheadenhomepage/resignation2.png",
          "/assets/game/col3row3/inheadenhomepage/negative2.png",
          "/assets/game/col3row3/inheadenhomepage/wonder2.png",
        ],
        default: "/assets/game/col3row3/inheadenhomepage/default.png",
      },
      denisInTechSpace: {
        images: [
          "/assets/game/col3row3/denisInTechSpace/integration.png",
          "/assets/game/col3row3/denisInTechSpace/killer.png",
          "/assets/game/col3row3/denisInTechSpace/suit.png",
          "/assets/game/col3row3/denisInTechSpace/strategic.png",
          "/assets/game/col3row3/denisInTechSpace/moon.png",
          "/assets/game/col3row3/denisInTechSpace/marble.png",
          "/assets/game/col3row3/denisInTechSpace/strategic2.png",
          "/assets/game/col3row3/denisInTechSpace/moon2.png",
          "/assets/game/col3row3/denisInTechSpace/marble2.png",
        ],
        default: "/assets/game/col3row2/denisInTechSpace/default.png",
      },
      footer: {
        images: [
          "/assets/game/col3row3/footer/at.png",
          "/assets/game/col3row3/footer/flatware.png",
          "/assets/game/col3row3/footer/exclusive.png",
          "/assets/game/col3row3/footer/elbow.png",
          "/assets/game/col3row3/footer/exploit.png",
          "/assets/game/col3row3/footer/tool.png",
          "/assets/game/col3row3/footer/elbow2.png",
          "/assets/game/col3row3/footer/exploit2.png",
          "/assets/game/col3row3/footer/tool2.png",
        ],
        default: "/assets/game/col3row1/footer/default.png",
      },
    },
  },

  {
    type: {
      col: 5,
      row: 3,
    },
    result: {
      inheadenHomePage: {
        images: images
          .slice(0, 15)
          .map((i) => `/assets/game/col5row3/inheadenhomepage/${i}.png`),
        default: "/assets/game/col3row1/inheadenhomepage/default.png",
      },
      denisTechSpace: {
        images: images
          .slice(0, 15)
          .map((i) => `/assets/game/col5row3/denisInTechSpace/${i}.png`),
        default: "/assets/game/col3row1/denisInTechSpace/default.png",
      },
      footer: {
        images: images
          .slice(0, 15)
          .map((i) => `/assets/game/col5row3/footer/${i}.png`),
        default: "/assets/game/col3row1/footer/default.png",
      },
    },
  },

  {
    type: {
      col: 6,
      row: 4,
    },
    result: {
      inheadenHomePage: {
        images: images
          .slice(0, 24)
          .map((i) => `/assets/game/col6row4/inheadenhomepage/${i}.png`),
        default: "/assets/game/col3row1/inheadenhomepage/default.png",
      },
      denisTechSpace: {
        images: images
          .slice(0, 24)
          .map((i) => `/assets/game/col6row4/denisInTechSpace/${i}.png`),
        default: "/assets/game/col3row1/denisInTechSpace/default.png",
      },
      footer: {
        images: images
          .slice(0, 24)
          .map((i) => `/assets/game/col6row4/footer/${i}.png`),
        default: "/assets/game/col3row1/footer/default.png",
      },
    },
  },

  {
    type: {
      col: 6,
      row: 6,
    },
    result: {
      inheadenHomePage: {
        images: images
          .slice(0, 36)
          .map((i) => `/assets/game/col6row6/inheadenhomepage/${i}.png`),
        default: "/assets/game/col3row1/inheadenhomepage/default.png",
      },
      denisTechSpace: {
        images: images
          .slice(0, 36)
          .map((i) => `/assets/game/col6row6/denisInTechSpace/${i}.png`),
        default: "/assets/game/col3row1/denisInTechSpace/default.png",
      },
      footer: {
        images: images
          .slice(0, 36)
          .map((i) => `/assets/game/col6row6/footer/${i}.png`),
        default: "/assets/game/col3row1/footer/default.png",
      },
    },
  },
];

export default gameAsset;
